# Generated by Django 2.0.6 on 2018-07-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Class'},
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
