# Generated by Django 2.0.6 on 2018-07-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0004_studentattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
