# Generated by Django 2.0.6 on 2018-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0006_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
