# Generated by Django 2.0.6 on 2018-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0007_student_attendance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_attendance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
