# Generated by Django 2.0.6 on 2018-07-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0008_student_total_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='', max_length=30)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('uploaded_on', models.DateField(default='2000-01-1')),
            ],
            options={
                'verbose_name': 'Marks',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('taught_in_class', models.CharField(choices=[('pre-nursery', 'pre-nursery'), ('nursery', 'nursery'), ('kinder-garten', 'kinder-garten'), ('Grade - 1', 'Grade - 1'), ('Grade - 2', 'Grade - 2'), ('Grade - 3', 'Grade - 3'), ('Grade - 4', 'Grade - 4'), ('Grade - 5', 'Grade - 5'), ('Grade - 6', 'Grade - 6'), ('Grade - 7', 'Grade - 7'), ('Grade - 8', 'Grade - 8'), ('Grade - 9', 'Grade - 9'), ('Grade - X', 'Grade - X'), ('Grade - XI', 'Grade - XI'), ('Grade - XII', 'Grade - XII'), ('none', 'none')], default='none', max_length=30)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='class_studying',
            field=models.CharField(choices=[('pre-nursery', 'pre-nursery'), ('nursery', 'nursery'), ('kinder-garten', 'kinder-garten'), ('Grade - 1', 'Grade - 1'), ('Grade - 2', 'Grade - 2'), ('Grade - 3', 'Grade - 3'), ('Grade - 4', 'Grade - 4'), ('Grade - 5', 'Grade - 5'), ('Grade - 6', 'Grade - 6'), ('Grade - 7', 'Grade - 7'), ('Grade - 8', 'Grade - 8'), ('Grade - 9', 'Grade - 9'), ('Grade - X', 'Grade - X'), ('Grade - XI', 'Grade - XI'), ('Grade - XII', 'Grade - XII'), ('none', 'none')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher',
            field=models.CharField(choices=[('pre-nursery', 'pre-nursery'), ('nursery', 'nursery'), ('kinder-garten', 'kinder-garten'), ('Grade - 1', 'Grade - 1'), ('Grade - 2', 'Grade - 2'), ('Grade - 3', 'Grade - 3'), ('Grade - 4', 'Grade - 4'), ('Grade - 5', 'Grade - 5'), ('Grade - 6', 'Grade - 6'), ('Grade - 7', 'Grade - 7'), ('Grade - 8', 'Grade - 8'), ('Grade - 9', 'Grade - 9'), ('Grade - X', 'Grade - X'), ('Grade - XI', 'Grade - XI'), ('Grade - XII', 'Grade - XII'), ('none', 'none')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Darwin.Student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Darwin.Subjects'),
        ),
        migrations.AddField(
            model_name='marks',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Darwin.Teacher'),
        ),
    ]
