# Generated by Django 2.0.6 on 2018-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0011_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_status',
            field=models.BooleanField(default=True),
        ),
    ]
